library(glasso)
example(glasso)
a.orig <- readRDS(a, file="a.RDS")
identical(a, a.orig)
##saveRDS(a, file="a.RDS")
example(glassopath)
##saveRDS(a, file="ap.RDS")
ap.orig <- readRDS(file="ap.RDS")
identical(a, ap.orig)
q()
